default:
  image: 
    name: runmymind/docker-android-sdk
    entrypoint: [""]
stages:
  - test
  - release
test:
  stage: test
  script:
    - GRADLE_USER_HOME=/cache ANDROID_HOME=/android-sdk-linux ./gradlew --no-daemon assembleBasicPretixDebug --stacktrace
release:
  stage: release
  script:
    - cat $KSTORE | base64 -d > mca.jks
    - GRADLE_USER_HOME=/cache ANDROID_HOME=/android-sdk-linux ./gradlew --no-daemon assembleBasicPretixRelease --stacktrace
  artifacts:
    paths:
      - app/build/outputs/apk/basicPretix/release/*.apk
    expire_in: '6 weeks'
  only:
    - '/^v.*$/'
variables:
  GIT_SUBMODULE_STRATEGY: recursive
